var name1 :string = "ance";
console.log(name1);
var age1 :number = 22;
console.log(age1);
//name1=18;
var fruits:string[]=["apple","grapes","mango"];
console.log(fruits);
//fruits.push(12);
fruits.push("strawberry");
console.log(fruits);